### ISSUE TITLE
버그: docker 개발 환경과 배포 환경의 포트 겹침

### ISSUE THREAD

**Issue by Aqudi** [kookmin-sw/capstone-2021-3#128]
- common.yaml의 포트 설정과 docker-compose.dev.yaml 포트 설정 겹침
- 동일하게 80번 포트로 바인딩하려고 한다.

**Comment by Aqudi** [comment]
common.yaml 의 api 서비스에만 정의하도록 수정.
```yaml
  api: &backend
    build:
      dockerfile: docker/Dockerfile.api
      context: .
    image: ghcr.io/aqudi/capstone_inobus_api
    ports:
      - 80:80
 ```
